config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :goals do
    member do 
      get :status
      post :status
      get :done
      post :done
    end
    resources :payments, only: [:new, :show]
  end

  resources :pages
  
  get 'congratulations' => 'pages#congratulations'
  get 'referee' => 'pages#referee'

  root to: 'pages#home'

  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goal.rb
class Goal < ApplicationRecord
    belongs_to :user
    validates :deadline, :penalty, :title, :referee, presence: true
    monetize :price_cents
    # monetize :amount_cents
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  # belongs_to :user
  # belongs_to :goal

  # monetize :amount_cents
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :goals
  has_many :transactions
end

app/models/weight_goal.rb
class WeightGoal < ApplicationRecord
    # belongs_to :user

    # validates :current, :desired, :deadline, :penalty, :price, presence: true
    # monetize :price_cents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
  session["redirect_to"] || goals_path
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :new]
  before_action :store_url, only: [:new]
  before_action :set_goal, only: [:show, :edit, :update, :destroy, :done, :failed]
  before_action :set_user

  def index
    @body_image = "body-image-index"
    @goals = Goal.all
  end
  
  def create
    @goal = Goal.new(goal_params)
    # @goal.done ? true : false
    @goal.user_id = @user.id
    if @goal.save
      GoalMailer.with(goal: @goal).new_goal_email.deliver_now

      # goal = Goal.find(params[:goal_id])
      @goal.state = 'pending'
      @goal.user = current_user
      # goal = Goal.create!(state: 'pending', user: current_user)
    
      session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        line_items: [{
          name: current_user.name,
          amount: @goal.penalty * 100,
          currency: 'brl',
          quantity: '1',
          description: "Você só será cobrado se não cumprir sua meta dentro do prazo."
        }],
        success_url: request.base_url + "/congratulations",
        cancel_url: goal_url(@goal),
        customer_email: current_user.email
      ) 
      
      flash[:success] = "Thank you for your wishes! We'll get contact you soon!"
      @goal.update(checkout_session_id: session.id)
      User.create(email: @goal.referee, password: "123456")
      redirect_to new_goal_payment_path(@goal)
    else
      flash.now[:error] = "Your mailer form had some errors. Please check the form and resubmit."
      render "new"
    end

  end

  def new
    # @goal = Goal.where(done: false).find(params[:goal_id])
    unless current_user.present? 
      redirect_to new_user_session_path
    end
      @body_image = "body-image-weigth-goals"
      @goal = Goal.new(title: params[:goal])
  end

  def edit
  end

  def show
    @body_image = "body-image-show"
    @goal = Goal.find(params[:id])
    # if Transaction.where(goal: @goal).count.zero?
    #   redirect_to new_transaction_path(goal_id: @goal.id)
    #   return
    # end
  end

  def update
    @goal.update(goal_params)
    redirect_to goal_path(@goal)
  end

  def destroy
    @goal.destroy
    redirect_to goals_path
  end

  def status
    @body_image = "body-image-show"
    @goal = Goal.find(params[:id])
  end

  def done
    @body_image = "body-image-show"
    @goal.done = params[:done]
    @goal.save
    redirect_to referee_path
  end

  private

  def store_url
    session["redirect_to"] = request.original_url
  end

  def set_goal
    @goal = Goal.find(params[:id])
  end

  def set_user
    @user = current_user
  end

  def goal_params
    params.require(:goal).permit(:deadline, :penalty, :title, :referee, :done)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  	@body_image = "body-image-home"
  end

  def congratulations
  	@body_image = "body-image-congratulations"
  end

  def referee
  	@body_image = "body-image-congratulations"
  end

  def done
    @goal = Goal.find(params[:id])
    @goal.done = true
    @goal.save
    # @goal.done ? 
    # @goal = Goal.where(done: false).find(params[:goal_id])
    # @goal.done ? true : false
    # if params[:done] == 'false'
		# 	@goal = Goal.where(done: false)
		# else
		# 	render 'show'
		# end
  end

  def failed
    @goal = Goal.find(params[:id])
    @goal.done = false
    @goal.save
    # @goal.done ? 
    # @goal = Goal.where(done: false).find(params[:goal_id])
    # @goal.done ? true : false
    # if params[:done] == 'false'
		# 	@goal = Goal.where(done: false)
		# else
		# 	render 'show'
		# end
  end

  def new
    @page = Page.new
  end

  def show
    @goal = Goal.find(params[:id])
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
    def new
      @body_image = "body-image-transaction-new"
      @goal = Goal.where(state: 'pending').find(params[:goal_id])
    end

    def show
   	  @goal = Goal.find(params[:goal_id])
   	  @payment = Payment.find(params[:id])
    end
  end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
    # before_action :set_user

    # def create
    #     goal = Goal.find(params[:goal_id])
    #     transaction  = Transaction.create!(amount: goal.penalty, state: 'pending', goal_id: goal.id, user: current_user)
      
    #     session = Stripe::Checkout::Session.create(
    #       payment_method_types: ['card'],
    #       line_items: [{
    #         name: current_user.name,
    #         amount: goal.penalty * 100,
    #         currency: 'brl',
    #         quantity: '1',
    #         description: "Você só será cobrado se não cumprir sua meta dentro do prazo."
    #       }],
    #       success_url: transaction_url(transaction),
    #       cancel_url: transaction_url(transaction)
    #     )
      
    #     transaction.update(checkout_session_id: session.id)
    #     redirect_to new_transaction_payment_path(transaction)
    #   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/goals/done.html.erb
<%= render 'shared/navbar2' %>

<div class="container rounded-3 p-4">
  <div class="row">
    <div class="col bg-white text-center p-3">
        <h4>Tempo Restante</h4>
        <h2 attr-deadline="<%= @goal.deadline %>" id="countdown" class=" text-center text-dark rounded-3"></h2>
    </div>
    <div class="col bg-info p-3 text-center">
        <h2 class="text-center text-dark"><%= @goal.title%></h2>
    </div>
  </div>
  <div class="row">
    <div class="col bg-danger text-center text-white p-3">
        <h2 class="text-center text-white">Penalidade</h2>
        <h2 class="text-center text-white"><%= humanized_money_with_symbol(@goal.penalty) %></h2>
    </div>
    <div class="col bg-dark text-center p-3">
        <h2 class="text-center text-white">Prazo</h2>
        <h2 class="text-center text-white"><%= @goal.deadline.strftime("%d/%m/%Y")%></h2>
        <%# <h2 class="text-center text-dark"> + desafio</h2> %>
        <%# <h1><%= link_to "Home", root_path, class: 'btn btn-primary btn-lg'%></h1>
    </div>
    <div class="col bg-white text-center p-3">
        <h2 class="text-center text-dark">Status</h2>
        <h2 class="text-center text-danger"><%= @goal.done ? "FEITO" : "PENDENTE"%></h2>
                
        <% if @goal.done == false %>

        <%= link_to 'feito', done_goal_path(@goal), class: 'btn btn-primary',
                method: :done %>
        <% else %>

        <%= link_to 'failed', failed_goal_path(@goal), class: 'btn btn-danger',
                method: :failed %>
        <% end %>
        <%#= link_to 'feito' done_goal_path(done), class: btn btn-primary,
        #     method: :done,
        #     data: true
        # %>
    </div>
  </div>
</div>

    <%# EXEMPLO DE STIMULUS IN RAILS %>

    <%# <%= content_tag :div, nil, data: {controller: "hello"} do %>
        <%# <h1 data-target="hello.heading">This is the home page</h1> %>
        <%# <div class="btn btn-primary" data-action="click->hello#greet">Say Hello</div> %>
    <%# <% end %>

app/views/goals/index.html.erb
<%= render 'shared/navbar2' %>
<section>
  <div class="container"> <!-- Inicio container -->
    <div class="row">
      <% @goals.each do |goal| %>
      <div class="col-md-4">
         <div class="cards"> 
            <div class="card">
                <h3 class="card-title"><%= goal.title %></h3>
                <%= image_tag "assets/#{rand(4)}.jpg", style: 'height: 400px' %>
                <p class="card-desc">Assuma o compromisso <%= goal.title %><br><br>
                <%= link_to "#{goal.title}", goal_path(goal.id), class: "btn btn-warning text-white", style: 'font-size: 1.6rem;' %> <br><br>
                <%= link_to "Remover", goal_path(goal.id), method: :delete, class: "btn btn-warning text-white", style: 'font-size: 1.6rem;' %></p>
            </div>
         </div>
      </div> 
      <% end %>
    </div> 
    </div>
  </div><!-- fim do container -->
</section><!-- fim seção card -->

app/views/goals/new.html.erb
<div class="lead">
   <%= render 'shared/navbar2' %>
   <%= render "shared/form" %>
</div>

app/views/goals/show.html.erb
<%= render 'shared/navbar2' %>

<div class="container rounded-3 p-4">
  <div class="row">
    <div class="col bg-white text-center p-3">
        <%# <h3 class="text-dark text-center">Tempo Restante</h3> %>
          <h2 attr-deadline="<%= @goal.done ? "0" : @goal.deadline %>" id="countdown" class=" text-center text-dark rounded-3"></h2>
    </div>
    <div class="col bg-info p-3 text-center">
        <h2 class="text-center text-dark"><%= @goal.title%></h2>
    </div>
  </div>
  <div class="row">
    <div class="col bg-danger text-center text-white p-3">
        <h2 class="text-center text-white">Penalidade</h2>
        <h2 class="text-center text-white"><%= @goal.done ? "nenhuma" : humanized_money_with_symbol(@goal.penalty) %></h2>
    </div>
    <div class="col bg-dark text-center p-3">
        <h2 class="text-center text-white">Prazo</h2>
        <h2 class="text-center text-white"><%= @goal.deadline.strftime("%d/%m/%Y")%></h2>
    </div>
    <div class="col bg-white text-center p-3">
        <h2 class="text-center text-dark">Status</h2>
        <% if @goal[:done] == true %>
          <h2 class="text-center text-success">Feito</h2>
        <% elsif @goal[:done] == false %>
          <h2 class="text-center text-danger">Pendente</h2>          
        <% end %>
    </div>
  </div>
</div>

app/views/goals/status.html.erb
<%= render 'shared/navbarReferee' %>

<div class="container rounded-3 p-4">
  <div class="row">
    <div class="col-7 bg-white text-center p-3">
        <h2 class="text-center text-dark">Acabou o tempo! <br> </h2>
    </div>
    <div class="col-5 bg-info p-3 text-center">
        <h2 class="text-center text-dark"><%= @goal.title%></h2>
    </div>
  </div>
  
  <div class="row">

    <%= link_to done_goal_path(@goal, done: false),
      style: 'text-decoration: none !important;
              width: 30%;
              padding-right: 0px;
              padding-left: 0px;' do %>
      <div class="col bg-danger text-center text-white p-3">
          <h1 class="text-center text-dark"><br>NÃO<br><br></h1>
      </div>
    <% end %>

    <div class="col bg-dark text-center p-3">
        <h2 class="text-center text-white">Bruno cumpriu sua meta?</h2>
        <% if @goal[:done] == true %>
          <h2 class="text-center text-success">Feito</h2>
        <% elsif @goal[:done] == false %>
          <h2 class="text-center text-danger">Pendente</h2>          
        <% end %>
    </div>
    
    <%= link_to done_goal_path(@goal, done: true),
      style: 'text-decoration: none !important;
              width: 30%;
              padding-right: 0px;
              padding-left: 0px;' do %>
      <div class="col bg-success text-center p-3">
        <h1 class="text-center text-dark"><br>SIM<br><br></h1>
      </div>
    <% end %> 
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ulisses</title>
    <link href="data:image/x-icon;base64,AAABAAEAEBAQAAAAAAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAgAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAnHNrAFpjUgD///8A96WUAP/e1gD/vbUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAACAVVhUAAAAABTMzZVYAAABjMzNRM2AAAFMxM1ExEAAAUzFlZDVWAABTMxFDMzVgAFMzMzMzM1AABTMzMzURYAAgUzMzM1YAAAIGUzMzM2AAAAAGUzMzUAAAAAAGUzNQAAAAAAAGVUAAAAAAAAAAAAAAAAAAAAAADgfwAAgB8AAIAPAAAABwAAAAcAAAADAAAAAQAAAAEAAIABAACAAwAAwAEAAPABAAD8AQAA/wEAAP/DAAD//wAA" rel="icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_include_tag :defaults %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body class="<%= @body_image %>">
    <%= render 'shared/flashes' %>

    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/congratulations.html.erb
<div style="margin: 120px">
  <div class="row py-4">
    <div class="col">
      <h2 class="text-white">Parabéns!</h2> 
      <br>
      <h2 class="text-white">Você acaba de assumir um compromisso com seu futuro.</h2>
      <%= link_to "Home", root_path, class: 'new-b' %>
      <%= link_to "Minhas Metas", goals_path, class: 'new-b' %>
      <%= link_to "Criar Nova Meta", new_goal_path, class: 'new-b' %>
    </div>
  </div>
</div>

app/views/pages/done.html.erb
<%= render 'shared/navbar2' %>

<div class="container rounded-3 p-4">
  <div class="row">
    <div class="col bg-white text-center p-3">
        <h4>Tempo Restante</h4>
        <h2 attr-deadline="<%= @goal.deadline %>" id="countdown" class=" text-center text-dark rounded-3"></h2>
    </div>
    <div class="col bg-info p-3 text-center">
        <h2 class="text-center text-dark"><%= @goal.title%></h2>
    </div>
  </div>
  <div class="row">
    <div class="col bg-danger text-center text-white p-3">
        <h2 class="text-center text-white">Penalidade</h2>
        <h2 class="text-center text-white"><%= humanized_money_with_symbol(@goal.penalty) %></h2>
    </div>
    <div class="col bg-dark text-center p-3">
        <h2 class="text-center text-white">Prazo</h2>
        <h2 class="text-center text-white"><%= @goal.deadline.strftime("%d/%m/%Y")%></h2>
        <%# <h2 class="text-center text-dark"> + desafio</h2> %>
        <%# <h1><%= link_to "Home", root_path, class: 'btn btn-primary btn-lg'%></h1>
    </div>
    <div class="col bg-white text-center p-3">
        <h2 class="text-center text-dark">Status</h2>
        <h2 class="text-center text-danger"><%= @goal.done ? "FEITO" : "PENDENTE"%></h2>
                
        <% if @goal.done == false %>

        <%= link_to 'feito', done_page_path(@goal), class: 'btn btn-primary',
                method: :done %>
        <% else %>

        <%= link_to 'failed', failed_page_path(@goal), class: 'btn btn-danger',
                method: :failed %>
        <% end %>
        <%#= link_to 'feito' done_goal_path(done), class: btn btn-primary,
        #     method: :done,
        #     data: true
        # %>
    </div>
  </div>
</div>

    <%# EXEMPLO DE STIMULUS IN RAILS %>

    <%# <%= content_tag :div, nil, data: {controller: "hello"} do %>
        <%# <h1 data-target="hello.heading">This is the home page</h1> %>
        <%# <div class="btn btn-primary" data-action="click->hello#greet">Say Hello</div> %>
    <%# <% end %>

app/views/pages/home.html.erb
  <%= render 'shared/navbar' %>
    <section id="home" class="d-flex"> <!-- home -->
        <div class="container align-self-center" style="margin-top: 57px"><!-- inicio container -->
          <div class="row"> <!-- inicio row -->
            <div class="col-md-12 capa">
              <h1 id="effect">Assuma o controle.<br>Seja seu próprio ídolo.</h1>

              <form method="GET" action="<%=  new_goal_path  %>">
                    <div class="dropdown_goal">
                      <input type="text" id="goal" name="goal" class="form-select form-select-lg mb-3" placeholder="Qual é a sua meta?" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Qual é a sua meta?'">
                    </div>
                    <input type="submit" class="new-b" value="Assumir compromisso">
              </form>

            </div>
          </div><!-- fim row -->
        </div> <!-- fim container -->
    </section> <!-- fim home -->

<section id="saiba" class="caixa"> <!--inicio secão card -->
  <div class="container-card">
    <h2 style="color: gray;text-align: center;font-size: 2.8rem"> Depoimentos </h2>
    <p class="text-center">Experiências de guerreir@s do Ulisses</p>
    <div class="row">
        <div class="col-lg-4">
            <div class="card">
                <div class="face front-face"> <img src="https://i.imgur.com/o5uMfKo.jpg" class="profile">
                    <div class="pt-3 text-uppercase name"> Karina Nascimento </div>
                    <div class="designation">Arquiteta Design</div>
                </div>
                <div class="face back-face"> <span class="fas fa-quote-left"></span>
                    <div class="testimonial"> Queria muito realizar uma viagem para Europa e sempre arrumava desculpas para deixar pra depois, descobri no site que poderia colocar dinheiro para ajudar ongs...e isso me incentivou a saber mais sobre o site e realizar esse sonho de viajar. </div> <span class="fas fa-quote-right"></span>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="card">
                <div class="face front-face"> <img src="https://images.unsplash.com/photo-1600486913747-55e5470d6f40?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80" alt="" class="profile">
                    <div class="pt-3 text-uppercase name"> Marcelo Candido</div>
                    <div class="designation">Full Stack Developer Rails</div>
                </div>
                <div class="face back-face"> <span class="fas fa-quote-left"></span>
                    <div class="testimonial"> Conheci a plataforma através de um amigo e com o objetivo para parar de fumar em 1ano. Tive muito incentivo do meu amigo como arbitro para conseguir executar esse desafio. </div> <span class="fas fa-quote-right"></span>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="card">
               <div class="face front-face"> <img src="https://images.unsplash.com/photo-1557862921-37829c790f19?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1051&q=80" alt="" class="profile">
                    <div class="pt-3 text-uppercase name"> Roberto Andrade </div>
                    <div class="designation">Programador</div>
                </div>
                <div class="face back-face"> <span class="fas fa-quote-left"></span>
                    <div class="testimonial"> Sempre tive muita dificuldade em perder peso e graças a plataforma Ulisses consegui emagrecer 10kg em 6 meses com meu dinheiro em risco. Para quem busca desafio o Ulisses sem dúvidas e o caminho ideal. </div> <span class="fas fa-quote-right"></span>
                </div> 
            </div>
        </div>
    </div>
</div>
</section><!-- fim seção card -->

      
      <section id="recursos" class="caixa"> <!-- inicio recursos -->
        <div class="container"> <!-- inicio container -->
          <div class="row"> <!-- inicio row -->
            <div class="col-md-4">
              <h2>Fácil</h2>
              <h3>Buscar</h3>
              <p>Já sabe o quer fazer hoje? Quer mudar seus hábitos?</p>

              <h3>Navegar</h3>
              <p>Veja como dar um up na sua vida, temos a ferramenta para você!</p>

              <h3>Descobrir</h3>
              <p>Veja o que seus amigos estão achando sobre sua mudança.</p>
            </div>
          </div><!-- fim row -->
        </div><!-- fim container -->
      </section><!-- fim recursos -->

      <section id="saiba" class="caixa"> <!-- inicio da seção saiba -->
        <div class="container">
          <div class="row video">
            <div class="col-md-6 d-flex">
              <div class="align-self-start">
                  <h2>O que é o Ulisses?</h2>
                  <p>
                  Ulisses é uma plataforma de compromisso para ajudá-lo a atingir seus objetivos.Inspirado nas dificuldades que as pessoas têm em conseguir cumprir suas metas.
                  </p>
              </div>
            </div>
              <div class="col-md-6">
                <h3>Vídeo: Motivacional</h3>
                <iframe width="560" height="315" src="https://www.youtube.com/embed/wnHW6o8WMas" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
              </div> 
          </div>
        </div>
      </section><!-- fim da seção saiba -->

      <footer>
        <div class="container"> 
          <div class="row">
            <div class="col-2">
              <div class=""><%= image_tag "SOS Mata Atlantica.png", style: 'width: 50px;' %></div>
              <div class="mt-4"><%= image_tag "fraternindade.png", style: 'width: 90px;' %></div>
              <div class="mt-4"><%= image_tag "Atados logo.png", style: 'width: 90px;' %></div>
            </div>
            <div class="col-2 ms-3 ps-3">
              <h3>Ulisses</h3>
              <ul class="navbar-nav">
                <li><a href="#">Sobre</a></li>
                <li><a href="#">Empregos</a></li>
                <li><a href="#">Imprensa</a></li>
                <li><a href="#">Novidades</a></li>
              </ul>
            </div>
            <div class="col-2">
              <h3>Comunidade</h3>
              <ul class="navbar-nav">
                <li><a href="#">Artistas</a></li>
                <li><a href="#">Desenvolvimento</a></li>
                <li><a href="#">Marcas</a></li>
              </ul>
            </div>
            <div class="col-2">
              <h3>Links Uteis</h3>
              <ul class="navbar-nav">
                <li><a href="#">Ajuda</a></li>
                <li><a href="#">Presentes</a></li>
                <li><a href="#">Player da web</a></li>
              </ul>
            </div>
            <div class="col-3">
              <ul>
                <li>
                  <%= image_tag("facebook.png") %>
                </li>
                <li>
                  <%= image_tag("twitter.png") %>
                </li>
                <li>
                  <%= image_tag("instagram.png") %>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </footer>

app/views/pages/show.html.erb
<%= render 'shared/navbar2' %>

<div class="container rounded-3 p-4">
  <div class="row">
    <div class="col bg-white text-center p-3">
        <h4>Tempo Restante</h4>
        <h2 attr-deadline="<%= @goal.deadline %>" id="countdown" class=" text-center text-dark rounded-3"></h2>
    </div>
    <div class="col bg-info p-3 text-center">
        <h2 class="text-center text-dark"><%= @goal.title%></h2>
    </div>
  </div>
  <div class="row">
    <div class="col bg-danger text-center text-white p-3">
        <h2 class="text-center text-white">Penalidade</h2>
        <h2 class="text-center text-white"><%= humanized_money_with_symbol(@goal.penalty) %></h2>
    </div>
    <div class="col bg-dark text-center p-3">
        <h2 class="text-center text-white">Prazo</h2>
        <h2 class="text-center text-white"><%= @goal.deadline.strftime("%d/%m/%Y")%></h2>
        <%# <h2 class="text-center text-dark"> + desafio</h2> %>
        <%# <h1><%= link_to "Home", root_path, class: 'btn btn-primary btn-lg'%></h1>
    </div>
    <div class="col bg-white text-center p-3">
        <h2 class="text-center text-dark">Status</h2>
        <h2 class="text-center text-danger"><%= @goal.done ? "FEITO" : "PENDENTE"%></h2>
                
        <% if @goal.done == false %>

        <%= link_to 'feito', done_page_path(@goal), class: 'btn btn-primary',
                method: :done %>
        <% else %>

        <%= link_to 'failed', failed_goal_path(@goal), class: 'btn btn-danger',
                method: :failed %>
        <% end %>
        <%#= link_to 'feito' done_goal_path(done), class: btn btn-primary,
        #     method: :done,
        #     data: true
        # %>
    </div>
  </div>
</div>

    <%# EXEMPLO DE STIMULUS IN RAILS %>

    <%# <%= content_tag :div, nil, data: {controller: "hello"} do %>
        <%# <h1 data-target="hello.heading">This is the home page</h1> %>
        <%# <div class="btn btn-primary" data-action="click->hello#greet">Say Hello</div> %>
    <%# <% end %>

app/views/payments/show.html.erb
<div class="container">
  <div class="row py-4">
    <div class="col">
      <h2>Parabéns!</h2> 
      <br>
      <h2>Você acaba de assumir um compromisso com seu futuro.</h2>
      <%# <ul class="list-unstyled"> %>
        <%# <li><strong>Penalidade</strong> <%= @transaction.created_at.to_date %></li>
        <%# <li><strong>Prazo</strong> <%= humanized_money_with_symbol @goal.deadline %></li>
        <%# <li><strong>Penalidade</strong> <%= humanized_money_with_symbol @transaction.amount %></li> %>
        <%# <li><strong>Prazo</strong> <%= @transaction.goal.goals_title %></li>
        <%# <li><strong>TOTAL</strong> <%= humanized_money_with_symbol @transaction.amount %></li>
        <%# </li> %>
      <%# </ul> %>
      <%# <p>Estimated delivery in <strong>2 business days</strong></p> %>
      <%# <%= link_to "Minhas metas", weight_goals_path, class: 'btn btn-primary' %>
      <%= link_to "Home", root_path, class: 'btn btn-primary' %>
      <%= link_to "Minhas Metas", goals_path, class: 'btn btn-primary' %>
      <%= link_to "Criar Nova Meta", new_goal_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/shared/_formGoal.erb
<%= form_tag goals_path do %>
  <%= hidden_field_tag 'goal_id', @goal.id %>
  <%= submit_tag 'ASSUMIR COMPROMISSO', class: 'btn btn-primary' %>
<% end %>